export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const REMOVE_START = 'REMOVE_START'
export const REMOVE_SUCCESS = 'REMOVE_SUCCESS'
export const REMOVE_ITEM = 'REMOVE_ITEM'

export const START_CHANGING_QUANTITY = 'START_CHANGING_QUANTITY'
export const CHANGED_QUANTITY_SUCCESS = 'CHANGED_QUANTITY_SUCCESS'
export const CHANGED_QUANTITY_FAIL = 'CHANGED_QUANTITY_FAIL'

export const START_SIZE = 'START_SIZE'
export const SIZE_SUCCESS = 'SIZE_SUCCESS'
export const SIZE_FAIL = 'SIZE_FAIL'