# Generated by Django 2.2.2 on 2019-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190704_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_price',
            field=models.FloatField(default=0),
        ),
    ]
