# Generated by Django 2.2.2 on 2019-07-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190704_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_size',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
