# Generated by Django 2.2.2 on 2019-07-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_orderitem_item_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_size',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
