# Generated by Django 2.2.2 on 2019-07-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190706_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_image',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
